import Bot from './Bot.js';

export default function loadCustomEmojis(client: Bot) {
    /* Emojis */
    client.em = {
        help: '<:help:864200218646675478>',
        neutral: '<:neutral:859844757160984636>',
        xmark: '<:xmark:819709577451798589>',
        check: '<:check:819708497083629578>',
        critical: '<a:critical:831968070788055101>',
        loadingfast: '<a:loadingfast:766093693823877151>',
        online: '<:online:819698342690291752>',
        offline: '<:offline:819698482415140874>',
        verified: '<:verified:854327524451287060>',
        partner: '<:partner:854336177595088896>',
        boost: '<:boost:854363426004271135>',
        boost0: '<:boost_tier_0:854353290069671976>',
        boost1: '<:boost_tier_1:854353264655728640>',
        boost2: '<:boost_tier_2:854353241411682315>',
        boost3: '<:boost_tier_3:854353214085660692>',
        booster: '<:booster:859417742108393523>',
        roles: '<:roles:854364000548290611>',
        owner: '<:owner:854365079498522645>',
        members: '<:members:854365038168244245>',
        verification: '<:verification:854366280840380417>',
        status: '<:status:854366374730268702>',
        emojis: '<:emojis:854367830463086622>',
        channels: '<:channels:854367781176082453>',
        textchannel: '<:text_channel:854367650607661086>',
        voicechannel: '<:voice_channel:854367711013765151>',
        settings: '<:settings:854384264363245568>',
        bot: '<:bot:856855630727348246>',
        nitro: '<:nitro:856855907077980160>',
        early_supporter: '<:early_supporter:856856231675559957>',
        bot_dev: '<:verified_bot_dev:856856354064957440>',
        hs_brilliance: '<:hypesquad_brilliance:856857446387154964>',
        hs_bravery: '<:hypesquad_bravery:856857295996190720>',
        hs_balance: '<:hypesquad_balance:856857228308119562>',
        hs_events: '<:hypesquad_events:856895790877376552>',
        discord_staff: '<:discord_staff:856863278671855626>',
        discord_mod: '<:discord_mod:856895711090049044>',
        bughunter: '<:bughunter:856895897425149962>',
        goldbughunter: '<:golden_bughunter:856895947769249793>',
        partner_owner: '<:discord_partner:856929481800810537>'
    }

    /* Reactions (Autogenerated from Emojis) */
    client.re = {}
    for (const emojiKey in client.em) {
        const emojiID = client.em[emojiKey].slice(1, -1).split(':')[2];
        client.re[emojiKey] = emojiID;
    }
}
